image: node:8

before_script:
  - npm install
  - npm install -g @angular/cli
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - apt-get -qq update -y
  - apt-get -qq install -y google-chrome-stable

cache:
  paths:
  - node_modules/

test_ui:
  stage: test
  tags:
    - linux
  script:
    - ng test developer --browsers ChromeHeadlessCi
    - ng build developer --prod
  artifacts:
    paths:
      - dist/developer
    expire_in: 1 day
    
